import { NodeData, Direction } from './types';

// Demo: Luna Campaign — cosmetic brand visual direction exploration
const DEMO_PROJECT_ID = 'demo-project';

export const DEMO_DIRECTIONS: Omit<Direction, 'nodeCount'>[] = [
  { id: 'dir-water', projectId: DEMO_PROJECT_ID, name: 'Water Drop', color: '#569cd6' },
  { id: 'dir-botanical', projectId: DEMO_PROJECT_ID, name: 'Botanical', color: '#6a9955' },
  { id: 'dir-minimal', projectId: DEMO_PROJECT_ID, name: 'Minimal Clean', color: '#dcdcaa' },
];

export const DEMO_NODES: NodeData[] = [
  // === Water Drop direction ===
  {
    id: 'node-w1',
    projectId: DEMO_PROJECT_ID,
    imageUrl: 'https://picsum.photos/seed/luna-water1/400/400',
    createdAt: Date.now() - 86400000 * 5,
    parentNodeId: null,
    directionId: 'dir-water',
    source: 'ai-generated',
    prompt: 'Elegant water droplet splash on dark surface, luxury cosmetic product photography, dramatic lighting',
    seed: null,
    intentTags: [],
    changeTags: [],
    note: '초기 컨셉 — 물방울 테마',
    status: 'reviewing',
    statusReason: null,
    versionNumber: 1,
    position: { x: 0, y: 0 },
  },
  {
    id: 'node-w2',
    projectId: DEMO_PROJECT_ID,
    imageUrl: 'https://picsum.photos/seed/luna-water2/400/400',
    createdAt: Date.now() - 86400000 * 4,
    parentNodeId: 'node-w1',
    directionId: 'dir-water',
    source: 'ai-generated',
    prompt: 'Crystal clear water droplet macro, soft blue gradient background, luxury skincare brand aesthetic',
    seed: null,
    intentTags: ['색감 조정'],
    changeTags: ['배경', '조명'],
    note: '블루 톤 강화',
    status: 'promising',
    statusReason: null,
    versionNumber: 2,
    position: { x: -120, y: 280 },
  },
  {
    id: 'node-w3',
    projectId: DEMO_PROJECT_ID,
    imageUrl: 'https://picsum.photos/seed/luna-water3/400/400',
    createdAt: Date.now() - 86400000 * 3,
    parentNodeId: 'node-w1',
    directionId: 'dir-water',
    source: 'ai-generated',
    prompt: 'Water ripple abstract pattern, golden hour lighting, minimal luxury cosmetic mood',
    seed: null,
    intentTags: ['분위기 전환'],
    changeTags: ['조명', '색상'],
    note: '골든아워 느낌 시도',
    status: 'dropped',
    statusReason: '브랜드 컬러와 맞지 않음',
    versionNumber: 3,
    position: { x: 120, y: 280 },
  },
  {
    id: 'node-w4',
    projectId: DEMO_PROJECT_ID,
    imageUrl: 'https://picsum.photos/seed/luna-water4/400/400',
    createdAt: Date.now() - 86400000 * 2,
    parentNodeId: 'node-w2',
    directionId: 'dir-water',
    source: 'ai-generated',
    prompt: 'Pristine water drop on glass surface, cool blue tones, high-end cosmetic packaging background',
    seed: null,
    intentTags: ['디테일 추가'],
    changeTags: ['텍스처'],
    note: '유리 질감 추가',
    status: 'final',
    statusReason: '가장 브랜드 이미지와 부합',
    versionNumber: 4,
    position: { x: -120, y: 560 },
  },

  // === Botanical direction ===
  {
    id: 'node-b1',
    projectId: DEMO_PROJECT_ID,
    imageUrl: 'https://picsum.photos/seed/luna-botan1/400/400',
    createdAt: Date.now() - 86400000 * 5,
    parentNodeId: null,
    directionId: 'dir-botanical',
    source: 'ai-generated',
    prompt: 'Lush green botanical garden close-up, morning dew on leaves, natural skincare ingredient imagery',
    seed: null,
    intentTags: [],
    changeTags: [],
    note: '보태니컬 초기 이미지',
    status: 'reviewing',
    statusReason: null,
    versionNumber: 1,
    position: { x: 400, y: 0 },
  },
  {
    id: 'node-b2',
    projectId: DEMO_PROJECT_ID,
    imageUrl: 'https://picsum.photos/seed/luna-botan2/400/400',
    createdAt: Date.now() - 86400000 * 3,
    parentNodeId: 'node-b1',
    directionId: 'dir-botanical',
    source: 'ai-generated',
    prompt: 'Minimalist botanical illustration, single leaf with water drops, white background, luxury beauty brand',
    seed: null,
    intentTags: ['단순화', '스타일 변경'],
    changeTags: ['배경', '레이아웃'],
    note: '미니멀하게 정리',
    status: 'promising',
    statusReason: null,
    versionNumber: 2,
    position: { x: 400, y: 280 },
  },

  // === Minimal Clean direction ===
  {
    id: 'node-m1',
    projectId: DEMO_PROJECT_ID,
    imageUrl: 'https://picsum.photos/seed/luna-min1/400/400',
    createdAt: Date.now() - 86400000 * 4,
    parentNodeId: null,
    directionId: 'dir-minimal',
    source: 'imported',
    prompt: null,
    seed: null,
    intentTags: [],
    changeTags: [],
    note: '경쟁사 레퍼런스 — 미니멀 스타일',
    status: 'reviewing',
    statusReason: null,
    versionNumber: 1,
    position: { x: 750, y: 0 },
  },
  {
    id: 'node-m2',
    projectId: DEMO_PROJECT_ID,
    imageUrl: 'https://picsum.photos/seed/luna-min2/400/400',
    createdAt: Date.now() - 86400000 * 2,
    parentNodeId: 'node-m1',
    directionId: 'dir-minimal',
    source: 'ai-generated',
    prompt: 'Ultra minimal product shot, white space, single cosmetic tube, soft shadow, clean typography area',
    seed: null,
    intentTags: ['구도 정리'],
    changeTags: ['레이아웃', '오브젝트'],
    note: '제품 중심 구도',
    status: 'reviewing',
    statusReason: null,
    versionNumber: 2,
    position: { x: 750, y: 280 },
  },
];
